### ISSUE TITLE
use default values

### ISSUE THREAD

**Issue by TobiasLueger** [hymhub/css-to-tailwind#2]
Could you convert the default values like 0.5rem/8px to 2 for padding for example.

So if you put in:
`padding: 0.5rem; `

it converts to:
`p-2`

Same for the margin attribute. Like you did for the width attributes.

**Comment by hymhub** [comment]
Thanks for the suggestion, I will consider adding the preset writing method in the future https://github.com/hymhub/css-to-tailwind/issues/1#issuecomment-1521836453

**Comment by hymhub** [comment]
Hey, the new version provides the `useAllDefaultValues` option, which can basically convert all default values
![image](https://user-images.githubusercontent.com/68531467/235294558-418fd243-8232-4d91-9a21-d2deb273f329.png)

**Comment by jamesscottbrown** [comment]
This is a useful feature, but I suggest enabling this setting by default.

I initially treid to use the tool and was confused why the output included classes like `border-[2px]`. It took me a while to realise that I needed to check the `useAllDefaultValues` box for conversions to work correctly.

**Comment by hymhub** [comment]
> This is a useful feature, but I suggest enabling this setting by default.
> 
> I initially treid to use the tool and was confused why the output included classes like `border-[2px]`. It took me a while to realise that I needed to check the `useAllDefaultValues` box for conversions to work correctly.

Updated v1.2.1, now `useAllDefaultValues` is true by default, and users who have modified the configuration before will not be affected, localStorage will remember the configuration
![image](https://github.com/hymhub/css-to-tailwind/assets/68531467/720292a4-5e25-421b-b3fd-5d32812cb4c8)

**Comment by johann-taberlet** [comment]
I think it doesn't works for font-size.
font-size: 3rem => text-[3rem] instead of text-5xl
