### ISSUE TITLE
Support output with prefix

### ISSUE THREAD

**Issue by uicrafts** [hymhub/css-to-tailwind#3]
Hey this is a handy tool, thank you for building it! Curious if there's a way (or you already have plans to support this) to specify the output should use a given prefix. It's common in large projects that are migrating to Tailwind to use a prefix in the Tailwind config file in order to avoid style conflicts, so I could see it being very useful to have an option to configure this.

**Comment by hymhub** [comment]
> Hey this is a handy tool, thank you for building it! Curious if there's a way (or you already have plans to support this) to specify the output should use a given prefix. It's common in large projects that are migrating to Tailwind to use a prefix in the Tailwind config file in order to avoid style conflicts, so I could see it being very useful to have an option to configure this.

Thanks for your suggestion, it is already planned

**Comment by hymhub** [comment]
Hey, this feature has been implemented
![image](https://user-images.githubusercontent.com/68531467/234895559-3787e1fc-a109-46f1-9754-7fb8dbdf5e05.png)
https://github.com/hymhub/css-to-tailwind#translatorconfig

**Comment by uicrafts** [comment]
Thank you!
