### ISSUE TITLE
`height` not using default values

### ISSUE THREAD

**Issue by jorgezreik** [hymhub/css-to-tailwind#6]
Love this repo, incredible job with it! I think it has a ton of potential.

If you're accepting community contributions, I could open a PR to fix this myself. Lmk what you think!

# Issue

`height` doesn't use default values in the same way `width` does.

# Reproduction

> Taken from the online demo

Input:
```css
* {
    width: 2rem;
    height: 2rem;
}
```

Output:
```plaintext
w-8
h-[2rem]
```

# Possible Cause

The [`height` configuration](https://github.com/hymhub/css-to-tailwind/blob/299d67722540d571e09c4e6cb4258d82148df047/npm/CssToTailwindTranslator.ts#L1147) has no reference to default values:
```typescript
val => (isUnit(val) ? `h-${getUnitMetacharactersVal(val, [CustomSelect.vw]) || `[${val}]`}` : '')
```

On the other hand, the [`width` configuration](https://github.com/hymhub/css-to-tailwind/blob/299d67722540d571e09c4e6cb4258d82148df047/npm/CssToTailwindTranslator.ts#L1977) does:
```typescript
val => (isUnit(val) ? `w-${(useAllDefaultValues && getRemDefaultVal(val)) || getUnitMetacharactersVal(val, [CustomSelect.vh]) || `[${val}]`}` : '')
```

Thus, I believe we can fix this issue by using the `useAllDefaultValues` function in the height configuration as well.

**Comment by hymhub** [comment]
You are right, it is now fixed, and subsequently if you find new problems, you can create PR directly if you wish, thank you for providing the problem
