### ISSUE TITLE
Typography configuration

### ISSUE THREAD

**Issue by njausteve** [hymhub/css-to-tailwind#8]
<img width="2050" alt="Screenshot 2023-06-26 at 2 22 58 PM" src="https://github.com/hymhub/css-to-tailwind/assets/5973499/f3df8a28-eaba-4d66-a076-03dee9bf101b">

How can I configure the config to output? `text-base`,  `font-semibold`, `leading-6`

**Comment by hymhub** [comment]
```json
{
  "font-weight": {
    "600": "font-semibold"
  },
  "font-size": {
    "1rem": "text-base"
  },
  "line-height": {
    "1.5rem": "leading-6"
  }
}
```
![image](https://github.com/hymhub/css-to-tailwind/assets/68531467/1622eb78-edda-4fbd-a8fc-943cebc013d0)

**Comment by njausteve** [comment]
Thanks @hymhub ❤️
